version: "2.2"

services:
  tsutsu:
    container_name: tsutsu
    build:
      context: ./
      dockerfile: dockerfile
    image: tsutsu:v1.0
    env_file:
      - .env-tsutsu
    volumes:
      - /home/ec2-user/tsutsu:/usr/src/app
    restart: always

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - tsutsu
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl:/etc/ssl
    restart: always
